"""extend projects

Revision ID: 211f8df6436a
Revises: d3d7dfc17b83
Create Date: 2026-07-16 17:43:22.734407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '211f8df6436a'
down_revision: Union[str, Sequence[str], None] = 'd3d7dfc17b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "projects",
        sa.Column(
            "technologies",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
    )

    op.add_column(
        "projects",
        sa.Column(
            "is_imported_from_github",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "projects",
        sa.Column(
            "source_github_repo_id",
            sa.UUID(),
            nullable=True,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'source_github_repo_id')
    op.drop_column('projects', 'is_imported_from_github')
    op.drop_column('projects', 'technologies')
    # ### end Alembic commands ###
