"""create_social_links_table

Revision ID: 36d431c0972d
Revises: dd38929e4561
Create Date: 2026-07-15 20:48:24.510586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d431c0972d'
down_revision: Union[str, Sequence[str], None] = 'dd38929e4561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('github', 'linkedin', 'twitter', 'website', 'youtube', 'instagram', 'facebook', 'dribbble', 'behance', 'other', name='socialplatform'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_links_user_id'), 'social_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_links_user_id'), table_name='social_links')
    op.drop_table('social_links')
    # ### end Alembic commands ###
