"""add_password_to_users

Revision ID: 9f7d8e0fb4cc
Revises: 75e7e6c54cd7
Create Date: 2026-07-03 20:28:47.302846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7d8e0fb4cc'
down_revision: Union[str, Sequence[str], None] = '75e7e6c54cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
