"""create github tables

Revision ID: d3d7dfc17b83
Revises: 3b7ef18db2ea
Create Date: 2026-07-16 11:26:53.257391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d7dfc17b83'
down_revision: Union[str, Sequence[str], None] = '3b7ef18db2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False),
    sa.Column('github_username', sa.String(length=200), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=True)
    op.create_table('github_repos',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['github_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repos_connection_id'), 'github_repos', ['connection_id'], unique=False)
    op.create_index(op.f('ix_github_repos_github_repo_id'), 'github_repos', ['github_repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_repos_github_repo_id'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_connection_id'), table_name='github_repos')
    op.drop_table('github_repos')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_table('github_connections')
    # ### end Alembic commands ###
